inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - 'client/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

StringLiterals:
  Enabled: false
