# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 972d8b7df2e45bf50d108c814ddeb0de95057a758789faea066754e7947b18b0a23931b72ef1feef4ea364a083580593495ae60bf5fb9bb908318e1e7246c759

test:
  secret_key_base: 5f411a356ad2afca623a5ab9354a7898797fb3ee3c707add24858ac682c381fdd19f994ed369f44e228c40a0aa4263bd7352d307e359477df7f03092e9cb9874

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
